# Penny Stock ML/DL Prediction Configuration

# Data Collection Settings
data:
  penny_stock_max_price: 5.0  # Maximum price for penny stocks (USD)
  min_volume: 100000  # Minimum daily volume
  min_market_cap: 1000000  # Minimum market cap (USD)
  lookback_days: 1095  # Historical data to collect (days) - 3 years
  update_frequency: 'daily'  # daily, hourly, or realtime

# Surge Detection Criteria
surge:
  # Define what constitutes a "surge"
  time_windows: [1, 3, 5, 7, 10]  # Days to look ahead
  surge_thresholds:
    mild: 0.15  # 15% increase
    moderate: 0.30  # 30% increase
    strong: 0.50  # 50% increase
    extreme: 1.00  # 100% increase
  default_threshold: 0.50  # Target: 50% surge in 10 days
  prediction_window: 10  # Hold for up to 10 trading days

  # Volume surge detection
  volume_surge_multiplier: 2.0  # 2x average volume

# Feature Engineering
features:
  # Technical Indicators
  technical_indicators:
    - 'RSI'
    - 'MACD'
    - 'Bollinger_Bands'
    - 'ATR'
    - 'ADX'
    - 'Stochastic'
    - 'OBV'
    - 'VWAP'
    - 'EMA_9'
    - 'EMA_21'
    - 'EMA_50'
    - 'SMA_20'
    - 'SMA_50'
    - 'SMA_200'

  # Price Action Features
  price_action:
    - 'price_change_1d'
    - 'price_change_3d'
    - 'price_change_5d'
    - 'price_change_10d'
    - 'volatility'
    - 'gap_up_down'

  # Volume Features
  volume:
    - 'volume_change'
    - 'volume_ma_ratio'
    - 'volume_spike'

  # Pattern Recognition
  patterns:
    - 'candlestick_patterns'
    - 'support_resistance'
    - 'trend_direction'

# Machine Learning Models
ml_models:
  random_forest:
    n_estimators: 200
    max_depth: 20
    min_samples_split: 10
    random_state: 42

  xgboost:
    n_estimators: 300
    max_depth: 8
    learning_rate: 0.1
    subsample: 0.8
    random_state: 42

  lightgbm:
    n_estimators: 300
    max_depth: 10
    learning_rate: 0.05
    num_leaves: 50
    random_state: 42

# Deep Learning Models
dl_models:
  lstm:
    sequence_length: 30
    layers: [128, 64, 32]
    dropout: 0.3
    batch_size: 64
    epochs: 100
    learning_rate: 0.001

  gru:
    sequence_length: 30
    layers: [128, 64, 32]
    dropout: 0.3
    batch_size: 64
    epochs: 100
    learning_rate: 0.001

  transformer:
    sequence_length: 30
    d_model: 128
    nhead: 8
    num_layers: 4
    dropout: 0.2
    batch_size: 32
    epochs: 100
    learning_rate: 0.0001

# Training Settings
training:
  test_size: 0.2
  validation_size: 0.1
  cross_validation_folds: 5
  early_stopping_patience: 10

# Prediction Settings
prediction:
  confidence_threshold: 0.7  # Minimum confidence for predictions
  top_n_stocks: 20  # Number of top predictions to return

# Backtesting
backtesting:
  initial_capital: 10000  # USD
  commission: 0.001  # 0.1% commission
  slippage: 0.001  # 0.1% slippage
  position_size: 0.1  # 10% of capital per position
  stop_loss: 0.05  # 5% stop loss (exit if -5%)
  take_profit: 0.50  # 50% take profit (exit when +50% reached)

# Logging
logging:
  level: 'INFO'
  log_file: 'logs/pennystock_ml.log'

# Output
output:
  models_dir: 'models'
  data_dir: 'data'
  results_dir: 'results'
  plots_dir: 'plots'
