stages:
  fetch_training_data:
    cmd: python ml/fetch_training_data.py
    deps:
      - ml/fetch_training_data.py
    outs:
      - ml/data/training_data.csv

  train:
    cmd: python ml/train_ai_score.py
    deps:
      - ml/train_ai_score.py
      - ml/data/training_data.csv
    params:
      - ml/params.yaml:
          - train.n_estimators
          - train.max_depth
          - train.learning_rate
    outs:
      - ml/models/model.pkl
      - ml/models/explainer.pkl
    metrics:
      - ml/metrics.json:
          cache: false

  evaluate:
    cmd: python ml/evaluate_model.py
    deps:
      - ml/evaluate_model.py
      - ml/models/model.pkl
      - ml/data/training_data.csv
    metrics:
      - ml/evaluation_metrics.json:
          cache: false
